### ISSUE TITLE
[Feature Request] Image import instead of generated Canny Edges

### ISSUE THREAD

**Issue by krummrey** [serycjon/vpype-flow-imager#10]
What if I want to start out with a hand sketch instead of the canny filtered lines?

**Comment by serycjon** [comment]
I don't plan to implement this, feel free to fork the code and implement it. (and possibly pullrequest, but I don't know if I would accept it - too much features start to creep in.)

You would add a new `edge_img_path` Path parameter [here](https://github.com/serycjon/vpype-flow-imager/blob/06fa00b8df46123657c487e915bb1d058c05d584/vpype_flow_imager/vpype_flow_imager.py#L117),
load the image and pass it through `draw_image` [here](https://github.com/serycjon/vpype-flow-imager/blob/06fa00b8df46123657c487e915bb1d058c05d584/vpype_flow_imager/vpype_flow_imager.py#L166), to `gen_edge_flow_field` [here](https://github.com/serycjon/vpype-flow-imager/blob/06fa00b8df46123657c487e915bb1d058c05d584/vpype_flow_imager/vpype_flow_imager.py#L351)
then stick the loaded edge image in [here](https://github.com/serycjon/vpype-flow-imager/blob/06fa00b8df46123657c487e915bb1d058c05d584/vpype_flow_imager/vpype_flow_imager.py#L277).
