### ISSUE TITLE
[Feature Request] Variable angle for the lines following the field

### ISSUE THREAD

**Issue by krummrey** [serycjon/vpype-flow-imager#11]
If the angle could be set to 90 dergrees the lines would run perpendicular to the others and both combined would make a great hatching.

**Comment by serycjon** [comment]
You can already use two perpendicular flow fields by using `--n_fields 4`. Or do you mean drawing one full flow field image with field A and then another one using a field perpendicular to A?

**Comment by krummrey** [comment]
[Demo Image](https://i.postimg.cc/y83fxDHd/Demo.jpg)
The red lines run perpendicular to the black lines. -nf 2 did not do that.

**Comment by serycjon** [comment]
I have edited the answer, try it with `-nf 4` - it probably still isn't the thing you are looking for, but maybe it will satisfy you.

**Comment by krummrey** [comment]
I figured it out. If you flip the image, process it and the flip it back, you'll get a 90 degree cross hatch.
[Demo Image](https://i.postimg.cc/RVbThf0R/Jan-Schraffur.png)

**Comment by jimmykl** [comment]
@krummrey I can't follow how you achieved that from your description – what do you mean by 'flip'? 

e.g. if you created a flow image from an image of a face, then flipped the image horizontally and processed it again, then overlaid the flow image results wouldn't you get a face which is mirrored down the centre?

**Comment by serycjon** [comment]
@krummrey very nice, I will try to implement your proposal in a moment.

**Comment by serycjon** [comment]
done. Try something like:
```
vpype flow_img -fs 42 examples/coffee.jpg flow_img -fs 42 --rotate 90 examples/coffee.jpg show
```

**Comment by krummrey** [comment]
> @krummrey I can't follow how you achieved that from your description – what do you mean by 'flip'?
> 
> e.g. if you created a flow image from an image of a face, then flipped the image horizontally and processed it again, then overlaid the flow image results wouldn't you get a face which is mirrored down the centre?

Mirror the image left-right, process it, mirror the svg back.
