### ISSUE TITLE
pipx install [all] failing

### ISSUE THREAD

**Issue by jimmykl** [serycjon/vpype-flow-imager#18]
I'm trying to install on on M1 Mac using `pipx inject vpype git+https://github.com/serycjon/vpype-flow-imager[all]` but get `zsh: no matches found: git+https://github.com/serycjon/vpype-flow-imager[all]`

I can install with `pipx inject vpype git+https://github.com/serycjon/vpype-flow-imager` but then have to use the kdt solver which isn't ideal for experimenting due to the slower processing.

**Comment by serycjon** [comment]
Hi Jimmy, zsh interprets the [all] as a regular expression and fails to find any match. This should get fixed by wrapping the url in single quotes, like this:

    pipx inject vpype 'git+https://github.com/serycjon/vpype-flow-imager[all]'
    
This tells zsh not to interpret the characters in any special way and take them as is.

**Comment by jimmykl** [comment]
Thanks Jonas

That seems to have hit another problem

```
pipx inject vpype 'git+https://github.com/serycjon/vpype-flow-imager[all]'
  error: subprocess-exited-with-error

  × git clone --filter=blob:none --quiet 'https://github.com/serycjon/vpype-flow-imager[all]' /private/var/folders/h_/wdvr7ycx1c1865m25rfz8yh80000gn/T/pip-req-build-3onr00_0 did not run successfully.
  │ exit code: 128
  ╰─> [1 lines of output]
      fatal: unable to access 'https://github.com/serycjon/vpype-flow-imager[all]/': The requested URL returned error: 400
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet 'https://github.com/serycjon/vpype-flow-imager[all]' /private/var/folders/h_/wdvr7ycx1c1865m25rfz8yh80000gn/T/pip-req-build-3onr00_0 did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Cannot determine package name from spec
'git+https://github.com/serycjon/vpype-flow-imager[all]'. Check package spec for errors.
```

I'm not sure why there's a forward slash at the end of `fatal: unable to access 'https://github.com/serycjon/vpype-flow-imager[all]/'` as I definitely only typed a '?

**Comment by serycjon** [comment]
fixed the installation instructions, it should work fine now.
