### ISSUE TITLE
Adaptive Canny Filter

### ISSUE THREAD

**Issue by krummrey** [serycjon/vpype-flow-imager#19]
I don't know how to make pull requests. But I have this improvement to offer:

```
def auto_canny(image, sigma=0.33):
	# compute the median of the single channel pixel intensities
	v = np.median(image)
	# apply automatic Canny edge detection using the computed median
	lower = int(max(0, (1.0 - sigma) * v))
	upper = int(min(255, (1.0 + sigma) * v))
	edged = cv2.Canny(image, lower, upper)
	# return the edged image
	return edged
```

call it in def gen_edge_flow_field(H, W, intensities)
```
    #automatic values for canny filter
    edges = auto_canny(intensities)
    #edges = cv2.Canny(intensities, 100, 200)
```
taken from: https://pyimagesearch.com/2015/04/06/zero-parameter-automatic-canny-edge-detection-with-python-and-opencv/

**Comment by serycjon** [comment]
I will leave this here.  If enough people want this version  (give thumbsup emote), I might change it.
I believe the default is ok and anybody can change it locally to best suit their needs.
