### ISSUE TITLE
Writing seed value(s) to SVG meta data

### ISSUE THREAD

**Issue by jimmykl** [serycjon/vpype-flow-imager#2]
Not sure if this is the place for a feature request but here's one:

It would be a beautiful thing if the seed value(s) could be written into the SVG metadata

I'm not sure if this is accomplished as I couldn't see anything which looked like it wrote the metadata in the plugin code.

**Comment by serycjon** [comment]
The svg output is performed by vpype. This vpype plugin just generates a collection of lines. But maybe we could add this functionality.
Could you show an example of such SVG with metadata?

**Comment by serycjon** [comment]
I have doublechecked and the SVGs already contain a <dc:source> tag with the invoked vpype command (including the seeds, if you have manually set them).
Would this be enough?

**Comment by jimmykl** [comment]
I spotted that which gave me this idea because only the manual seeds are included.

I like being able to view random fields to find one that interests me but then can't see the seed afterwards to get to use manually so I can tweak its other parameters.

An alternative could be a flag which outputs all the parameters, including seeds, after processing e.g. `--verbose` or something?

**Comment by serycjon** [comment]
You can use vpype's `-v` flag, which will print the vpype seed (which is used in this plugin, if you don't override it with your own using `-s` or `-fs`).

Another option is to run the program in a loop, trying different seeds, e.g. from 0 to 100. You can even run several of them in parallel using GNU parallel. Try:
`parallel vpype flow_img -s {} coffee.jpg write coffee_{}.svg ::: {0..100}`.

If you just want to pick general shape of the flow field, I would recommend doing that with pure white image (of the same size as your real image) and with fairly high `-Ms` to get fast preview.

**Comment by jimmykl** [comment]
Cool. Good tip re: previewing flow field, that's part of what I was hoping to achieve, thank you!

Will experiment with parallel but can already hear my laptop fans complaining, a good 'leave running overnight' job

**Comment by stuperbad** [comment]
is it possible to recover the random seed of a previous generation from the timestamp somehow? I don't see any seed info in the dc:source but I have the dc:date which mb is how the PRNG is set? (Crossing my fingers)

**Comment by serycjon** [comment]
sorry, I don't think so. The PRNG is probably seeded by time, but you won't be able to find the exact moment when it was seeded with the dc:date. If you don't specify any seed, vpype does this:
https://github.com/abey79/vpype/blob/2b87933bf8b7f2d5749d96306bb69a260f2df6c9/vpype_cli/cli.py#L246
