### ISSUE TITLE
Adaptive Kernel size for Darkfield

### ISSUE THREAD

**Issue by krummrey** [serycjon/vpype-flow-imager#20]
I don't know how to make pull requests. But I have this improvement to offer:

```
    #blur_kernel = 2 * 87 + 1
    blur_kernel = int(np.sqrt(H*W)/10)
    if (blur_kernel% 2) == 0:
        blur_kernel+=1
```
Resizes the Gaussian Blur to the image size

**Comment by serycjon** [comment]
Thanks, I changed it slightly to get similar kernel size with the default image size.
