### ISSUE TITLE
Installation problem Mac OS 

### ISSUE THREAD

**Issue by Unemontagne** [serycjon/vpype-flow-imager#24]
I am a pen plotter artist and a vpype user. My version is 1.12.1 installed in a virtual environment.

I have tried to install flow-imager using 
> pip install 'git+https://github.com/serycjon/vpype-flow-imager.git#egg=vpype-flow-imager[all]'

The installation seemed to be successful but "vpype -h" returns :
> vpype_flow_imager  † Warning: could not load plugin. See `vpype
>                        vpype_flow_imager --help`.

and 
> vpype_flow_imager --help
gives
> Warning: entry point could not be loaded. Contact its author for help.

**Comment by abey79** [comment]
I tried to reproduce with a pipx-installed version of vpype (`pipx inject vpype "git+https://github.com/serycjon/vpype-flow-imager.git#egg=vpype-flow-imager[all]"`) and could not reproduce.

Can you provide more information on your setup? Which python version are you using? How did you install it?

**Comment by jimmykl** [comment]
I've just setup a fresh machine using brew to install Python 3.8 then following the github instructions

```
python3.8 -m venv my_virtual_env
source my_virtual_env/bin/activate
pip install 'git+https://github.com/serycjon/vpype-flow-imager.git#egg=vpype-flow-imager[all]
```

but unfortunately for troubleshooting your issue this worked ok.

Things to check: 
Do you have python 3.8 installed?
Have you activated the right venv? 
Instead of `vpype_flow_imager --help` try `vpype flow_img --help`?

**Comment by abey79** [comment]
Oh, I actually didn't notice this at first. Having `vpype_flow_imager` showing up in `vpype --help` is really weird. It should show up as `flow_img` indeed.

**Comment by Unemontagne** [comment]
I have Python 3.9.0 installed.

I use pyenv instead of venv. Could it be the problem ?
I have a virtual environment called « vpype ».

I have tried 

> vpype flow_img --help

That returned :

> Usage: vpype [OPTIONS] COMMAND1 [ARGS]... [COMMAND2 [ARGS]...]...
> 
> Error: No such command 'flow_img'.

And I also tried some others commands :

> vpype vpype_flow_imager input.jpg write output.svg
> vpype flow_imager input.jpg write output.svg
> vpype vpype_flow_imager input.jpg write output.svg

Which gave me the same error message.

Finally, I tried a pipx install but pipx does not recognize my virtual environment.

**Comment by abey79** [comment]
I'm not really sure what's going on. Two things though:

1) 3.9.0 should really be updated, this being the first point release of the 3.9 series. The last point release is 3.9.16. I dont know if that explains anything.

2) You dont need to create nor activate any virtual environment with pipx, as it handles that automatically behind the scene. Simply run `pipx install 'vpype[all]'` to install vpype. Then the `vpype` command should be globally available. Then, run `$ pipx inject vpype 'git+https://github.com/serycjon/vpype-flow-imager.git#egg=vpype-flow-imager[all]'` to install the plug-in. I advise installing a newer version of python first though.

**Comment by Unemontagne** [comment]
Hi

I was finally able to reinstall vpype and get it working.
I removed all versions of python 3 and all existing virtual environments.
I installed python 3.10 and vpype following the instructions.

Everything is fine now !

Thank you for your answers.

Long live vpype !
