### ISSUE TITLE
flow_img fails without -tf set

### ISSUE THREAD

**Issue by bcongdon** [serycjon/vpype-flow-imager#3]
If I try to run `vpype flow_img img.jpg` without the `-tf` flag set, I get the following error:
```
File ".../vsketch/venv/lib/python3.8/site-packages/vpype_flow_imager/vpype_flow_imager.py", line 228, in d_test_fn
    return d_sep_fn(*args, **kwargs) / test_frequency
TypeError: unsupported operand type(s) for /: 'float' and 'NoneType'
```

It looks like that flag might need a default value? Running `vpype flow_img -tf 2 img.jpg` seems to work

(As an aside, thanks for making this! It's a great addition to the vpype ecosystem 😄 )

**Comment by serycjon** [comment]
Thanks for the report, fixed.

**Comment by kevin227227** [comment]
what does the "-tf" parameter modify in the drawing ?

**Comment by serycjon** [comment]
You probably do not have to touch it. It changes a frequency of streamline distance tests. The image darkness dictates how far apart should the streamlines be.  This distance gets divided by the `tf` parameter to compute streamline step size. With low `tf`, the streamline distance check will occur less frequently and the streamlines will get closer together than they should. You get better precision with higher `tf`, but the computation will be slower.
