### ISSUE TITLE
Feature request: timeout field generation

### ISSUE THREAD

**Issue by jimmykl** [serycjon/vpype-flow-imager#5]
I would like a way to timeout the generation of the flow field after a set period – either a number of seconds `timeout 10` or even `timeout 50%` if that's possible

Why? Sometimes cancelling before it is fully resolved creates some cool effects. It would also allow generating an animation of the flow field in progress…

I tried using bash `timeout` but that cancels the entire command so`show` or `write` are not triggered

**Comment by jimmykl** [comment]
If there *is* a way to do this with bash rather than adding it to flow_img let me know!

**Comment by serycjon** [comment]
You can `timeout -s SIGINT 20s vpypecommand`. That sends SIGINT after 20 seconds, which should be the same as pressing ctrl+c after 20 seconds and should cancel the flow computation while allowing the rest to run.

For animation it would be better to just drop parts of the fully generated svg (assuming you don't linesort, I believe that the lines in the svg file should be in the generated order.
