### ISSUE TITLE
Python version (question)

### ISSUE THREAD

**Issue by mariana-s-fernandes** [serycjon/vpype-flow-imager#8]
Does this require Python 3.8 to run? Or could it be installed in an older version?
Asking because I am having trouble installing hnswlib

**Comment by mariana-s-fernandes** [comment]
Regarding the hnswlib installation problem, I've fixed it by running `sudo apt-get install python3.7-dev` (after updating the `apt-get`)

**Comment by serycjon** [comment]
I don't know, did not try. The code contains python f-strings on few places, so it needs at least python3.6, but these can be easily converted to older python `"string".format()` stuff and maybe it then could run even in python 2 - the main issue will be the library dependencies.

Let me know if you (successfully or not) test the flow imager on different python versions.

**Comment by krummrey** [comment]
I am able to run the script using Python 3.6.9 on Ubuntu 18.04.

**Comment by mariana-s-fernandes** [comment]
Closing the issue, the version was not the problem with my instalation. It ran successfully with 3.7
